
name: .NET Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
  
    runs-on: windows-latest
                             
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Execute unit tests
      run: dotnet test

    - name: Build Project
      run: dotnet build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Build Debug
        path: LogBook-WPF\bin\Debug\net8.0-windows10.0.18362.0
